/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#006193',
        'on-primary':                 '#ffffff',
        'primary-container':          '#1b7ab5',
        'on-primary-container':       '#fdfcff',
        'primary-fixed':              '#cce5ff',
        'primary-fixed-dim':          '#92ccff',
        'on-primary-fixed':           '#001d31',
        'on-primary-fixed-variant':   '#004b73',
        'secondary':                  '#b4271d',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#fe5c4a',
        'on-secondary-container':     '#610001',
        'secondary-fixed':            '#ffdad5',
        'secondary-fixed-dim':        '#ffb4a9',
        'on-secondary-fixed':         '#410000',
        'on-secondary-fixed-variant': '#910807',
        'tertiary':                   '#7d5400',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#9e6a00',
        'on-tertiary-container':      '#fffbff',
        'tertiary-fixed':             '#ffddb1',
        'tertiary-fixed-dim':         '#fdba4e',
        'on-tertiary-fixed':          '#291800',
        'on-tertiary-fixed-variant':  '#614000',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'surface':                    '#f7f9ff',
        'surface-dim':                '#d8dadf',
        'surface-bright':             '#f7f9ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f1f4f9',
        'surface-container':          '#eceef3',
        'surface-container-high':     '#e6e8ed',
        'surface-container-highest':  '#e0e2e8',
        'on-surface':                 '#181c20',
        'on-surface-variant':         '#404850',
        'outline':                    '#707881',
        'outline-variant':            '#c0c7d1',
        'inverse-surface':            '#2d3135',
        'inverse-on-surface':         '#eef1f6',
        'inverse-primary':            '#92ccff',
        'surface-tint':               '#006397',
        'surface-variant':            '#e0e2e8',
        'background':                 '#f7f9ff',
        'on-background':              '#181c20',
      },
      fontFamily: {
        sans: ['Public Sans', 'sans-serif'],
      },
      spacing: {
        'gutter': '24px',
      },
      boxShadow: {
        'level-1': '0px 4px 20px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
}
